[package]
name = "pinors"
version = "0.1.0"
authors = ["pinosaur"]
description = ""
repository = "https://github.com/MrPicklePinosaur/matsuba"
edition = "2018"

[workspace]
members = ["crates/*"]

[dependencies]

[lib]
name = "argparse"
path = "crates/argparse/src/lib.rs"
crate-type = ["lib"]
